template_path: templates/service.yaml

# hooks:
#   before_create:
#     - !cmd "cd lambdas/put_birthday && make artifact"
#     - !cmd "cd lambdas/process_birthdays && make artifact"
#   before_update:
#     - !cmd "cd lambdas/put_birthday && make upload"
#     - !cmd "cd lambdas/process_birthdays && make artifact"

parameters:
  ArtifactBucket: !stack_output deployment::DeploymentBucketName
  PutBirthdayArtifact: put_birthday/lambda.zip
  ProcessBirthdaysArtifact: put_birthday/lambda.zip
  BirthdaysDatabaseArn: !stack_output database::BirthdaysDatabaseArn
  BirthdaysDatabaseName: !stack_output database::BirthdaysDatabaseName
  BirthdaybotKmsKeyArn: !stack_output encryption::BirthdaybotKmsKeyArn
  WebhookUrl: "AQICAHhavxItRk46L7PNOLIWTzfOZK0BMd5VNZjkC0+HqGf4rgHgWvSG0BWn0lQeYv86nBlnAAAAzDCByQYJKoZIhvcNAQcGoIG7MIG4AgEAMIGyBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKRQu30QcYq6nLzB6AIBEICBhDlhsdoujO5EcVbjd8r3rhiFH+m7xt/6bTjpfDB05f+UkNkHew/bUSMUtDgUqcE3VETYMiT6yoVmIIZStSeeCr3BR8RVbwKEzcWRm/6uJwOSUCNof0T39XA76tH58opMm7l60X6sUs+BOwn60smtRf1Cl3HTGP5QgdLindZD4czEWyfB8A=="
